In [55]:
import numpy as np
import pandas as pd
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split

In [56]:
col_names = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 
             'Uniformity of Cell Shape', 'Marginal Adhesion', 
             'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin','Normal Nucleoli',
            'Mitoses', 'Class']
df = pd.read_csv('breast-cancer-wisconsin.data',names=col_names)
# Reaplace all question marks with large negative value
df.replace('?',-99999,inplace=True)
df.drop(['Sample code number'],1,inplace=True)
# Display
df

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...
694,3,1,1,1,3,2,1,1,1,2
695,2,1,1,1,2,1,1,1,1,2
696,5,10,10,3,7,3,8,10,2,4
697,4,8,6,4,3,4,10,6,1,4
698,4,8,8,5,4,5,10,4,1,4

In [69]:
X = np.array(df.drop(['Class'],1))
y = np.array(df['Class'])

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
X_train_transformed

array([[ 2.02838346,  0.2995061 ,  0.28957312, ..., -0.57777378,
         0.04124139, -0.32425801],
       [ 1.66945141,  2.25768045,  2.30456946, ..., -0.1599529 ,
         0.04124139, -0.32425801],
       [-1.20200501, -0.67958108, -0.71792505, ..., -0.99559467,
        -0.60816532, -0.32425801],
       ...,
       [-0.12520886, -0.67958108, -0.71792505, ..., -0.99559467,
        -0.60816532, -0.32425801],
       [ 0.2337232 , -0.67958108, -0.71792505, ..., -0.57777378,
        -0.60816532, -0.32425801],
       [-1.20200501, -0.67958108, -0.71792505, ..., -0.99559467,
        -0.60816532, -0.32425801]])

In [71]:
clf = svm.SVC(C=1)

In [72]:
clf.fit(X_train_transformed,y_train)
X_test_transformed = scaler.transform(X_test)
confidence = clf.score(X_test_transformed, y_test)
confidence

0.9714285714285714

In [61]:
example_measures = np.array([[4,2,1,1,1,2,3,2,1]])
example_measures = example_measures.reshape(len(example_measures), -1)
prediction = clf.predict(example_measures)
prediction

array([4])